name: neural_env
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - blas=1.0=openblas
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.17=py311h1854d6b_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6d0c2b6_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h37d8d59_0
  - libcxx=19.1.7=haebbb44_3
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libffi=3.4.4=hecd8cb5_1
  - libgfortran=5.0.0=11_3_0_hecd8cb5_28
  - libgfortran5=11.3.0=h9dfd629_28
  - libopenblas=0.3.29=h3f8574a_0
  - libsodium=1.0.20=hfdf4475_0
  - llvm-openmp=19.1.7=h5048363_2
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h923df54_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy-base=1.24.3=py311he799857_2
  - openssl=3.6.0=h230baf5_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py311h62e9434_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.13=hbff2529_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=2_cp311
  - pyzmq=27.1.0=py311h0ab6910_0
  - readline=8.3=h49f2429_0
  - scipy=1.12.0=py311h7695dc5_0
  - setuptools=78.1.1=py311hecd8cb5_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hc8b0dd6_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=h3a5a201_0
  - tornado=6.5.2=py311hf197a57_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - zeromq=4.3.5=h6c33b1e_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4b97444_1
  - pip:
      - aiodns==3.5.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - attrs==25.4.0
      - ccxt==4.5.22
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - coincurve==21.0.0
      - contourpy==1.3.3
      - cryptography==46.0.3
      - cycler==0.12.1
      - filelock==3.20.0
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - multidict==6.7.0
      - networkx==3.6
      - numpy==1.26.4
      - pandas==2.3.3
      - patsy==1.0.2
      - pillow==12.0.0
      - propcache==0.4.1
      - pyarrow==22.0.0
      - pycares==4.11.0
      - pycparser==2.23
      - pyparsing==3.2.5
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - scikit-learn==1.3.2
      - statsmodels==0.14.6
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - torch==2.2.2
      - tqdm==4.67.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - yarl==1.22.0
